api_platform:
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    patch_formats:
#        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
        versions: [3]
    version: '1.0.0'
    collection:
        pagination:
            client_partial: true
            partial_parameter_name: 'partial'
            items_per_page: 10

    exception_to_status:
        App\Exception\ArticleForbiddenException: 403
