framework:
    cache:
#        app: cache.adapter.redis
#        default_redis_provider: '%env(REDIS_URL)%'
        prefix_seed: 'msu'
        pools:
            redis.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
