version: '3'

services:
  msu-php:
    build:
      context: .docker/php
      dockerfile: test.Dockerfile
    container_name: msu-php
    volumes:
      - ./:/var/www/html
      - ".docker/php/php-${APP_ENV}.ini:/usr/local/etc/php/custom.d/php.ini"
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    user: 1000:1000

  msu-server:
    image: nginx:1.17-alpine
    container_name: msu-server
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
      - .docker/nginx/log:/var/www/log
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - msu-php

  msu-redis:
    container_name: msu-redis
    image: redis:5.0.8-alpine
    restart: always
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

  msu-db:
    image: mysql:5.7
    container_name: msu-db
    volumes:
      - .docker/mysql:/var/lib/mysql
      - .docker/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "3310:3306"
    command: --innodb-use-native-aio=0
